name: RBE Output
description: Mark an output to be downloaded by RBE
author: bentekkie

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: file
  color: blue

# Define your inputs here.
inputs:
  name:
    description: The name of the output
    required: true
  type:
    description: The type of the output. One of fileset, container or buildgraph
    required: true
    default: fileset
  path:
    description: The path to the output
    required: true
  output_location:
    description: The location of the output. Fully qualified GCS path if type is fileset or a buildgraph, otherwise it is an artifact registry docker path.
    required: true

runs:
  using: node24
  main: dist/index.js
